name: DataMiner DeployOnly Automation

# Prerequisite: secret 'DATAMINER_DEPLOY_KEY' necessary on Repository or Organization level.
# Value is the API-key generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  CD:   
    name: CD
    environment: staging
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3

       - name: Skyline DataMiner Deploy Action Development
         if: github.ref_type == 'branch'
         uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
         with:
           # Stage deploy
           stage: All
           # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
           api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
           solution-path: ./AutomationScript.sln
           artifact-name: ${{ github.repository }} ${{ github.ref_name }}_B${{ github.run_number }}
           build-number: ${{ github.run_number }}
           
       - name: Skyline DataMiner Deploy Action Release
         if: github.ref_type == 'tag'
         uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
         with:
           # Stage deploy
           stage: All
           # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
           api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
           solution-path: ./AutomationScript.sln
           artifact-name: ${{ github.repository }} ${{ github.ref_name }}
           version: ${{ github.ref_name }}
           
